// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ooad.DTO;
//
//    var giangvien = Giangvien.FromJson(jsonString);

namespace ooad.DTO
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class GIANGVIEN
    {
        [JsonProperty("idgiangvien")]
        public long Idgiangvien { get; set; }

        [JsonProperty("idkhoa")]
        public long Idkhoa { get; set; }

        [JsonProperty("idhopdong")]
        public long Idhopdong { get; set; }

        [JsonProperty("idchuyennganh")]
        public long Idchuyennganh { get; set; }

        [JsonProperty("idtrinhdo")]
        public long Idtrinhdo { get; set; }

        [JsonProperty("tengv")]
        public string Tengv { get; set; }

        public static List<GIANGVIEN> FromJson(string json) => JsonConvert.DeserializeObject<List<GIANGVIEN>>(json, ooad.DTO.Converter.Settings);
    }

}
