// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ooad.DTO;
//
//    var hocphan = Hocphan.FromJson(jsonString);

namespace ooad.DTO
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class HOCPHAN
    {
        [JsonProperty("idhocphan")]
        public string Idhocphan { get; set; }

        [JsonProperty("tenhocphan")]
        public string Tenhocphan { get; set; }

        [JsonProperty("sotinchi")]
        public long Sotinchi { get; set; }

        [JsonProperty("sotietlythuyet")]
        public long Sotietlythuyet { get; set; }

        [JsonProperty("sotietthuchanh")]
        public long Sotietthuchanh { get; set; }

        [JsonProperty("sotiettuhoc")]
        public long Sotiettuhoc { get; set; }

        [JsonProperty("sotietthamquan")]
        public long Sotietthamquan { get; set; }

        [JsonProperty("idkhoa")]
        public long Idkhoa { get; set; }

        public static List<HOCPHAN> FromJson(string json) => JsonConvert.DeserializeObject<List<HOCPHAN>>(json, ooad.DTO.Converter.Settings);
    }

   
}
