// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ooad.DTO;
//
//    var phonghoc = Phonghoc.FromJson(jsonString);

namespace ooad.DTO
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class PHONGHOC
    {
        [JsonProperty("idphonghoc")]
        public long Idphonghoc { get; set; }

        [JsonProperty("idchucnang")]
        public long Idchucnang { get; set; }

        [JsonProperty("idsucchua")]
        public long Idsucchua { get; set; }

        [JsonProperty("sohieu")]
        public string Sohieu { get; set; }
        public static List<PHONGHOC> FromJson(string json) => JsonConvert.DeserializeObject<List<PHONGHOC>>(json, ooad.DTO.Converter.Settings);
    }

   
}
